### ISSUE TITLE
'Not Found' error returned when performing initial sync of Issues

### ISSUE THREAD

**Issue by rgduncan** [instantish/notion-github-action#54]
<sub>[Discuss in #**public-issue-54--not-found-error-returned-when-performing-initial-sync-of-issues**](https://slack.com/app_redirect?team=TJ5G67VHU&channel=C038PA1BNDN)</sub>

### Describe the bug

When attempting to perform an initial sync of existing Issues in the respective repository, a `Not Found` error is returned

### Steps to reproduce

1. Follow all steps in guide
2. Verify that organization and repo token have all required permissions
3. Manually run `workflow_dispatch` from Github UI
4. Job sets up properly
5. `Finding Github Issues... Error: Not Found`
6. Workflow fails

### Expected behavior

Workflow completes and syncs Issues to Notion DB

### Setup
```
Current runner version: '[2](https://github.com/SensibleWeather/protect/runs/5631848204?check_suite_focus=true#step:1:2).288.1'
Operating System
Virtual Environment
Virtual Environment Provisioner
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'instantish/notion-github-action@v1.2.0'
```

### Run Job
```
Run instantish/notion-github-action@v1
  with:
    notion-token: ***
    notion-db: ***
context event: workflow_dispatch
context action: __instantish_notion-github-action
payload action: undefined
Starting...
Checking for issues already in the database...
Finding Github Issues...
Error: Not Found
```

**Comment by rgduncan** [comment]
I used the `Release 1.1.2` tag and now it works, though I get a lot of warnings about conflicts and I had to run the initial sync multiple times before all isuess were reflected. It might be worth deleting or renaming the `1.2.0` tag since the semver suggests it's a later version than `1.1.2`.

**Comment by marissamarym** [comment]
thanks for submitting this! we’ve renamed the tag so the releases are in order, and pushed another release
